Fix meta image
```
ValueError: Missing staticfiles manifest entry for 'images/logo.png'
```

Perhaps we need to dynamically read this at runtime instead of defining
it as a static property since collectstatic has to run first.

This crashes the worker and celery-beat.